### ISSUE TITLE
ReAPI binary is missing

### ISSUE THREAD

**Issue by victorjvs** [AMXX-pl/BasePack#1]
Hello,

I was checking the files in the pack and noticed that the ReAPI binary "reapi_amxx_i386.so" is missing.

I've corrected it here, but you still need to launch it on the branch

**Comment by TheDoctor0** [comment]
Hello Victor.
Are you sure about that?
This binary is available on both [master](https://github.com/AMXX-pl/BasePack/blob/master/cstrike/addons/amxmodx/modules/reapi_amxx_i386.so) branch and in the latest release:
![7zFM_UbwDZYMZpu](https://user-images.githubusercontent.com/16612504/90986990-b0561a80-e587-11ea-9d29-9087e5772f74.png)

**Comment by victorjvs** [comment]
Hello!

I downloaded the zip again and checked that it really is there!

Thanks for the quick response.
