### ISSUE TITLE
Error shows in console

### ISSUE THREAD

**Issue by Ali0mer** [AMXX-pl/BasePack#10]
SZ_GetSpace: Tried to write to an uninitialized sizebuf_t ??? 

This error shows and server gets crashed 

I did a lot of research about it and i find out that the error shows if a bot joined the game, so i tried to disable the bot plugin, the problem is fixed 
Also isee some servers using my same mod (ZP) and have that kind of error only my server.. And they use old version of amxmod

So maybe the error bcz of this amxmodz version? And can it be fixed?

**Comment by TheDoctor0** [comment]
Hey @Ali0mer, this BasePack is only a collection of modules.
If you experience issues related to AmxModX then report it here at https://github.com/alliedmodders/amxmodx.
