### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Damigeana** [AMXX-pl/BasePack#2]
L 08/29/2020 - 16:21:10: [AMXX] Modules list not found (file "addons/amxmodx/configs/modules.ini ")
L 08/29/2020 - 16:21:10: Error parsing gameconfig file "cstrike/addons/amxmodx/data /gamedata/common.games.txt":
L 08/29/2020 - 16:21:10: Error 1 on line 0, col 0: Stream failed to open
L 08/29/2020 - 16:21:10: Could not read common.games gamedata: File could not be opened: unknown
ReGameDLL version: 5.18.0.474-dev
L 08/29/2020 - 16:21:11: -------- Mapchange to de_dust2 --------
L 08/29/2020 - 16:21:11: [AMXX] FlagManager: Cannot open file "cstrike/addons/amxmodx/configs /cmdaccess.ini" (FILE pointer null!)
L 08/29/2020 - 16:21:11: [AMXX] Modules list not found (file "addons/amxmodx/configs/modules.ini ")
L 08/29/2020 - 16:21:11: [AMXX] Plugins list not found (file "addons/amxmodx/configs/plugins.ini ")

Is ok?

**Comment by TheDoctor0** [comment]
Those errors clearly suggest that you didn't upload all the BasePack files to your server.

**Comment by Damigeana** [comment]
> Those errors clearly suggest that you didn't upload all the BasePack files to your server.

No, the problem is you gona have 2 core.ini. One from your server and one from base_pack.
The solution is found is to delete the core.ini from amxmodx/config so was just remaining the one from base_pack.

**Comment by TheDoctor0** [comment]
> The solution is found is to delete the core.ini from amxmodx/config so was just remaining the one from base_pack.

BasePack should be uploaded to a fresh server without AMXX installed yet. By doing that you created a problem!
